
@api = http://localhost:3000/task

GET {{api}}

###
GET {{api}}/5

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "title": "New Task",
    "descriptions": "New Task Description"
}

###
DELETE {{api}}/6

###
PUT {{api}}/1
content-type: application/json

{
    "title": "Crear mi Backend",
    "descriptions": "Description updated with PUT"
}